<?php

namespace vox\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MusicReleaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicReleaseRepository extends EntityRepository
{
}
